#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    
    design:

        form_theme: 'horizontal'
        
        menu:
            - label: 'Gestion du site'
            - { entity: 'User', icon: 'users' , label: 'Utilisateurs'}
            - { entity: 'Produits', icon: 'book'}
            - { entity: 'Categorie', icon: 'list-ol'}
            - { entity: 'Panier', icon: 'shopping-basket'}
            - { entity: 'Commandes', icon: 'truck'}
            - { entity: 'Contenu', icon: 'cubes'}
            
            - label: 'Liens éditeur'
            - {label: Symfony,url: "https://symfony.com/", target: "_blank", icon: "thumbs-o-up"}
            
            - label: 'Liens internes'
            - {label: 'Bookstore',route: "home", icon: "mouse-pointer"}
            
    entities:
           #Entity class name     
        User:
            class: App\Entity\User
            list:
                title: "Liste des utilisateurs"
                fields:
                    - {property: 'user_name',type: 'text'}
                    - {property: 'password'}
                    - {property: 'email', type: 'email'}
                    - {property: 'role'}
            form:
                title: "ajout d'un utilisateur"
                
                fields:
                    - {property: 'user_name',type: 'text'}
                    - {property: 'password'}
                    - {property: 'email', type: 'email'}
                    - {property: 'role', type: 'choice', type_options:
                        {choices: {'Utilisateur':'ROLE_USER', 'Admin':'ROLE_ADMIN'}}}
        
        Produits:
            class: App\Entity\Produits
            list:
                title: "Liste des produits"
                fields:
                    - {property: 'pro_id' , label: 'Id' , type_options: { required: true }}
                    - {property: 'pro_nom',type: 'text' , label: 'Nom' , type_options: { required: true }}
                    - {property: 'pro_prix' , label: 'Prix' , type_options: { required: true }}
                    - {property: 'pro_image',type: 'text' , label: 'Lien image' , type_options: { required: true }}
                    - {property: 'pro_resume' ,type: 'text' , label: 'Résumé' , type_options: { required: true }}
                    - {property: 'pro_stock',type: 'integer' , label: 'Stock' , type_options: { required: true }}
                    - {property: 'cat_id' , label: 'Catégorie' , type_options: { required: true }}
            form:
                title: "ajout d'un produit"
                fields:
                    - {property: 'pro_nom',type: 'text' , label: 'Nom', type_options: { required: true }}
                    - {property: 'pro_prix', type: 'integer' , label: 'Prix' , type_options: { required: true }}
                    - {property: 'pro_image',type: 'text' , label: 'Lien image' , type_options: { required: true }}
                    - {property: 'pro_resume' ,type: 'text' , label: 'Résumé' , type_options: { required: true }}
                    - {property: 'pro_stock',type: 'integer' , label: 'Stock' , type_options: { required: true }}
                    - {property: 'cat_id', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Categorie'}, label: 'Catégorie' }
        
        Categorie:
            class: App\Entity\Categorie
            list:
                title: "Liste des catégories"
                fields:
                    - {property: 'cat_id'}
                    - {property: 'cat_libelle',type: 'text'}

            form:
                title: "ajout d'une catégorie"
                
                fields:
                    - {property: 'cat_libelle',type: 'text'}
        
        Panier:
            class: App\Entity\Panier
            list:
                title: "Paniers des utilisateurs"
                fields:
                    - {property: 'pan_id'}
                    - {property: 'pro_id',type: 'text' , label: 'Produit'}
                    - {property: 'user_id', label: 'Utilisateur'}
                    - {property: 'pan_quantite', label: 'Quantité'}
            form:
                title: "ajout d'un panier"
                
                fields:
                    - {property: 'pro_id',type: 'text' , label: 'Produit'}
                    - {property: 'user_id' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\User'}, label: 'Utilisateur'}
                    - {property: 'pan_quantite',type: 'integer', label: 'Quantité'}
                    
        Commandes:
            disabled_actions: ['delete']
            class: App\Entity\Commandes
            list:
                title: "Commandes"
                fields:
                    - {property: 'com_id'}
                    - {property: 'user_id', label: 'Utilisateur'}
                    - {property: 'com_date', label: 'Date'}
            form:
                title: "Modification commande"
                
                fields:
                    - {property: 'user_id' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\User'},  label: 'Utilisateur'}
                    - {property: 'com_date', type: 'date' , label: 'Date'} 
                    
        Contenu:
            disabled_actions: ['delete']
            class: App\Entity\Contenu
            list:
                title: "Contenu des commandes"
                fields:
                    - {property: 'contenu_id'}
                    - {property: 'com_id' , label: 'Commande'}
                    - {property: 'pro_id', label: 'Produit'}
                    - {property: 'contenu_quantite', label: 'Quantité'}
                    - {property: 'contenu_prix', label: 'Prix'}

            form:
                title: "Modification du contenu de la commande"
                
                fields:
                    - {property: 'com_id',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Commande'}, label: 'Commande' }
                    - {property: 'pro_id',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Produits'}, label: 'Produit'}
                    - {property: 'contenu_quantite', type: 'integer' , label: 'Quantité'}
                    - {property: 'contenu_prix', type: 'integer', label: 'Prix'}
                    
                            
                 
                            

                            
            

   
                